In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
one_dimensional_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
two_dimensional_array = np.array([[1, 2], [3, 4], [5, 6]])
two_dimensional_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
ones_array = np.array([np.ones])
print("ones_array:", ones_array[1:10])
zeros_array = np.array([np.zeros])
zeros_array[1:10]

ones_array: []


array([], dtype=object)

In [17]:
sequence_array = np.arange(1, 10, 1, 'int64')
sequence_array # prints sequence or a numpy array
# np.arange(start, stop, step/difference between two consecutive numbers, dtype)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=100, size=6, dtype='int64')
random_integers_between_50_and_100
# generates random integers from low to high in the form of a numpy array of some size and dtype

array([73, 59, 92, 55, 80, 74])

In [20]:
random_floating_points_between_0_and_1 = np.random.random([6])
random_floating_points_between_0_and_1
# generates a numpy array of size 6 between 0 and 1

array([0.22406554, 0.26204131, 0.79160062, 0.50164632, 0.04562437,
       0.93534082])

In [21]:
random_floating_points_between_2_and_3 = np.random.random([6]) + 2.0
random_floating_points_between_2_and_3
# generates a numpy array of floating points of size 6 between 0 and 1 and then adds 2.0 
# to each one in the array to get floating points between 2 and 3

array([2.20723942, 2.73479261, 2.66457967, 2.62972979, 2.23018508,
       2.39972497])

In [22]:
random_integers_between_150_and_300 = np.random.randint(low=50, high=100, size=6, dtype='int64') * 3
random_integers_between_150_and_300
# generates a numpy array of integers of size 6 between 50 and 100 and then multiplies each
# one in the array with 3 to get random integers between 150 and 300

array([240, 195, 237, 150, 165, 258])

# Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
2. Assign 15 values to a NumPy array named label such that:
   
   label = (3)(feature) + 4

For example, the first value for label should be:
  
  label = (3)(6) + 4 = 22

In [27]:
feature = np.arange(start=6, stop=21, dtype='int64')
print(feature)
label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


# Task 2: Add Some Noise to the Dataset
To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. 

To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [32]:
noise = np.random.random([15]) * 4 - 2
print(noise)
label = noise + label
print(label)

[-1.70544326 -1.44628975  1.51560352 -0.47403047 -1.39644     1.43725818
 -1.16779632 -0.22865178 -1.26791315  1.8277882   1.45209259  0.85997016
 -0.72273581 -1.04840598 -1.08695185]
[20.29455674 23.55371025 29.51560352 30.52596953 32.60356    38.43725818
 38.83220368 42.77134822 44.73208685 50.8277882  53.45209259 55.85997016
 57.27726419 59.95159402 62.91304815]
